name: UHPlugin
description: Ultra Hardcore plugin
main: me.azenet.UHPlugin.UHPlugin
version: 1.1.1 §cdev§r
author: "Amaury Carrade"
authors: [azenet, "João Roda"]

awareness:
  - !@UTF8

softdepend:
  - WorldBorder
  - SpectatorPlus
  - dynmap
  - ProtocolLib

commands:
   uh:
      description: Ultra Harcore base command
      usage: /uh <subcommand> - see /uh for available subcommands.
   t:
      description: Allows an user to send a message to his team.
      usage: /t <message>
   
   g:
      description: Allows an user to send a message to everyone.
      usage: /g <message>
   
   togglechat:
       description: Allows an user to toggle the chat between the global chat and a team chat.
       usage: /togglechat

permissions:
    uh.*:
        description: Gives access to all Ultra Hardcore commands.
        children:
            uh.build: true
            uh.about: true
            uh.start: true
            uh.shift: true
            uh.team: true
            uh.addspawn: true
            uh.generatewalls: true
            uh.freeze: true
            uh.border: true
            uh.heal: true
            uh.healall: true
            uh.tpback: true
            uh.resurrect: true
            uh.spec: true
            uh.teamchat.self: true
            uh.teamchat.others: true
    
    uh.teamchat.*:
        description: Allows an user to use the team chat for both his own team and other teams.
        children:
            uh.teamchat.self: true
            uh.teamchat.others: true
    
    uh.build:
        description: Allows an user to build before the beginning of the game
        default: op
    uh.about:
        description: Prints some informations about the plugin and the translation.
        default: true
    uh.start:
        description: Allows an user to start the game with /uh start
        default: op
    uh.shift:
        description: Allows an user to shift an episode using /uh shift
        default: op
    uh.team:
        description: Allows an user to manage the teams with /uh team *
        default: op
    uh.addspawn:
        description: Allows an user to add a spawn point
        default: op
    uh.generatewalls:
        description: Allows an user to generate the walls around the map
        default: op
    uh.freeze:
        description: Allows an user to freeze the players
        default: op
    uh.border:
        description: Allows an user to manage the border using /uh border *
        default: op
    uh.heal:
        description: Allows an user to heal a player using /uh heal <player> [half-hearts]
        default: op
    uh.healall:
        description: Allows an user to heal ALL players using /uh healall [half-hearts]
        default: op
    uh.resurrect:
        description: Allows an user to resurrect another player with /uh resurrect <player>
        default: op
    uh.tpback:
        description: Allows an user to teleport back a player to his death point with /uh tpback <player> [force]
        default: op
    uh.spec:
        description: Allows an user to manage spectators using /uh spec *
        default: op
    
    uh.teamchat.self:
        description: Allows an user to send a private message to their team.
        default: true
    uh.teamchat.others:
        description: Allows an user to send a private message to other team, and to see the private chat of any team.
        default: op
